### ISSUE TITLE
Road to a unixfs-like in golang with ADLs

### ISSUE THREAD

**Issue by warpfork** [ipld/go-ipld-prime#258]
This issue is a short checklist/roadmap for the major areas of work needed in order to make something "unixfs-like" happen in golang and be implemented almost entirely in ADLs.

#### "unixfs-like"

By "unixfs-like", I mean both of: we can reimplement a feature-parity unixfsv1 (like what go-ipfs does) this way; and we would also reuse the majority of these code and components in building a "unixfsv2"; and most importantly, someone _else_ could grab most of the components we'll need here and build _their own_ custom evolution of what they consider a "unixfs-like" with minimal hurdles.

#### "implemented as ADLs"

By "implemented almost entirely in ADLs" I mean: there should be a few pieces of code which implement key functionality by making complex structures act "like a `map`-kind node" and "like a `bytes`-kind node".  So: directories?  Map.  Files?  Bytes.  Even though either of them can be sharded?  Yep.  And that should, when composed, make a unixfs-like system almost trivial to assemble.

The desirable outcomes of this are two (or three): one, it means things like pathing and traversals and selectors over them are _already defined_ (because it's just "working over a map", etc); two, it's a very clear abstraction which allows for reuse when someone wants to make a new system.  (Also, three, in the longer run -- we hope to make ADLs into a language-agnostic plugin system.  But that is not today :)  Today we are happy to implement it in one language, get something working, and plan to move on later.)

## Roadmap

Without further ado, some checkboxes...

- [x] Already have: the write API for map ADLs
  - (it's just `NodeBuilder`/`NodeAssembler`)
- [x] Already have: the read API for map ADLs
  - (it's just `Node`)
- [x] Already have: the read implementation of the ADL for directories
  - it's over in https://github.com/ipfs/go-unixfsnode
- [ ] Need: the write implementation of the ADL for directories
  - probably should continue in https://github.com/ipfs/go-unixfsnode
- [ ] Need: the read API for bigbytes ADLs
  - this will go here in go-ipld-prime
  - should be implemented by some kind of feature detection.  (We already have the API for bytes as slices, but we need one that works with seeking and streaming.)
- [ ] Need: the write API for bigbytes ADLs
  - this will go here in go-ipld-prime
  - should be implemented by some kind of feature detection.  (We already have the API for bytes as slices, but we need one that works with seeking and streaming.)
- [ ] Need: the read implementation of ADL for unixfs files
  - might already exist over in https://github.com/ipfs/go-unixfsnode ?  (not sure)
  - ideally, uses [the FBL spec](https://ipld.io/specs/advanced-data-layouts/fbl/) and can read many things... but we might end up needing a special one-off for unixfsv1, too.
- [ ] Need: the write implementation of the ADL for unixfs files…
  - this will be fun: probably this should be constructed with chunker functions as a parameter!
- [ ] Want: an API convention for efficient "append" to map ADLs
  - should be something we can do relatively late in the development pipeline, because we should do it with feature detection anyway.
  
Not all of this work has to take place in this repo, and several parts of it can be started without blocking on other parts.  It also doesn't all have to be done by the same people.  This is just a tracking and roadmap-sharing issue.

**Comment by willscott** [comment]
in terms of getting to a working implementation, we can defer the two 'bigbytes' items, because the existing https://github.com/ipfs/go-ipfs-chunker interface provides `[]byte` for each individual node as it streams out of the file. As long as we don't keep all in-progress nodes in memory, which is a different problem, the direct handling of `io.Reader` can probably come after the MVP.

* the read implementation for unixfs files doesn't exist yet at go-unixfsnode.

**Comment by warpfork** [comment]
We get a lot of value out of having just the directory/map stuff done.  I would think it's good to focus fire on that first.  Yes.

There's probably no _harm_ in writing the file chunking stuff into the current `Node` and `NodeAssembler` APIs that are non-streaming -- because somewhere between 99% and 100% of that code _does_ need to be written anyway.

I think we'll need the `io.Reader` (or `io.ReadSeeker`?) for in and out of big bytes to see the full success for files, though.  Because yeah, the current non-streaming APIs don't really make it possible to have an abstraction and still have good memory usage.

**Comment by willscott** [comment]
Yep, i agree that we do eventually need a cleaner interaction with `io.Reader` / `io.Writer`, especially at the ADL level. 

The main thing I was pointing out is that initially it'll probably be desirable to use the existing set of chunker implementations, and since those are not fully streaming, it probably is another nudge that we can push off figuring out the final streaming designs since we'll end up with that crutch anyway for a while.

**Comment by guseggert** [comment]
Yes the issue is here: https://github.com/ipfs/go-ipfs/issues/8455

**Comment by warpfork** [comment]
There's a https://github.com/ipfs/go-unixfsnode/ repo nowaday, which I believe has even more of these features.
