### ISSUE TITLE
v0.18.0 release checklist

### ISSUE THREAD

**Issue by rvagg** [ipld/go-ipld-prime#448]
* [x] Add new h3 to `CHANGELOG.md` under **Released Changes** with curated and subsystem-grouped list of changes and links to relevant PRs
  * [x] Highlight any potentially breaking or disruptive changes under "🛠 Breaking Changes", including extended descriptions to help users make compatibility judgements
  * [ ] Add special-thanks call-outs to contributors making significant contributions
* [x] Update **Planned/Upcoming Changes** section to remove completed items and add newly upcoming, but incomplete items
* [x] Bump version number appropriately in `version.json`
* [x] Propose release via pull request, merge after enough time for async global feedback
* [x] Create GitHub [release](https://github.com/ipld/go-ipld-prime/releases) with the new tag, copying the new `CHANGELOG.md` contents
* [x] Announce on relevant Discord/Matrix/Slack channel(s)
* [ ] (Optional) Announce to shipped@protocol.ai
